### ISSUE TITLE
Increasing/Customizing the number of reference point on the X axis 

### ISSUE THREAD

**Issue by kubapilch** [mp-007/kivy_matplotlib_widget#1]
Is there a way to increase the number of reference points on the axis? 

I have this graph 
![obraz](https://user-images.githubusercontent.com/21139232/159178141-4857467e-9161-476f-b5a1-38489cdd35f6.png)

And I want to have more points on X axis so it's nor 4000 to 5000 byt 4100 4200 4300 etc.

**Comment by mp-007** [comment]
You can increase the number of label like this:
```
from matplotlib.ticker import MaxNLocator

...

self.ax1.xaxis.set_major_locator(MaxNLocator(nbins=10))
```

You can add this in your graph generator file is you want (note: nbins is the maximum number of labels).

Also if you want to customize your x axis label you can do something like this:
https://stackoverflow.com/a/12608937

Also, almost all the thing you can do matplotlib can be done with my widget.
