### ISSUE TITLE
Matplotlib events

### ISSUE THREAD

**Issue by don6019** [mp-007/kivy_matplotlib_widget#2]
Is there any way to access matplotlib events ? For example 'pick_event' so it is possible to interact with the plotted data.

def on_pick(event):
    line = event.artist
    xdata, ydata = line.get_data()
    ind = event.ind
    print('on pick line:', np.array([xdata[ind], ydata[ind]]).T)

**Comment by mp-007** [comment]
The way I use kivy matplotlib is with the kivy on_touch and on_move events. So I don't need to handle matplotlib events because it's necessary. Maybe if I put an example in the repo, it will more clear.

**Comment by mp-007** [comment]
I have had a new cursor example.
![image](https://user-images.githubusercontent.com/19823482/164080091-ad45679a-4da8-48bb-a90b-949a4773974a.png)
