### ISSUE TITLE
weakproxy error

### ISSUE THREAD

**Issue by Sahil-pixel** [mp-007/kivy_matplotlib_widget#21]
File "kivy/weakproxy.pyx", line 32, in kivy.weakproxy.WeakProxy.__getattr__
 AttributeError: 'MatplotFigure' object has no attribute 'main_home'

**Comment by mp-007** [comment]
main_home is not a function from MatplotFigure. It's only use for MatplotFigureSubplot because this widget can handle multiple axes. I don't know your purpose but if you can give me a working example, I will be able to understand your issue.

**Comment by mp-007** [comment]
@Sahil-pixel 

Found this error in my min/max example (https://github.com/mp-007/kivy_matplotlib_widget/tree/main/examples/example_minmax_option). I've made a fix in this commit 2d1476ac83911e2195aa8f1cd87e8e27fb121bf8

**Comment by Sahil-pixel** [comment]
Great.👍
