### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by oulfik** [mp-007/kivy_matplotlib_widget#3]
Thanks for your contribution! I am currently using matplotlib without any external widgets in my kivy app. It works fine with simple plots but not when plotting spectrograms with librosa and matplotlib (constant freezes). I would like to incorporate your widget but the license is missing. Could you add maybe a permissive license like MIT?

**Comment by mp-007** [comment]
Here's an example with matplotlib spectrogram (on windows)
![ice_video_20220421-113857](https://user-images.githubusercontent.com/19823482/164499460-047d4585-dc8e-472d-ad2b-719c814989e9.gif)
