### ISSUE TITLE
There is an accumulative distance error when pan with mouse

### ISSUE THREAD

**Issue by ShannonZ** [mp-007/kivy_matplotlib_widget#6]
Comparing with the behaviour of a interactively matplotlib backend, the pan operation in this repo has an accumulative error.

**Comment by mp-007** [comment]
the code was base on this https://stackoverflow.com/a/19829987

**Comment by mp-007** [comment]
I saw the error. I will try to fix it. Thanks for reporting this behavior.

**Comment by mp-007** [comment]
by divisive dx and dy by 2, seem to fix the behavior with the mouse. I need to validate this with a finger touch.
![image](https://user-images.githubusercontent.com/19823482/170295479-5a92f61e-e45f-42a3-ab5c-faa5642d850f.png)

**Comment by ShannonZ** [comment]
> by dividing dx and dy by 2, seem to fix the behavior with the mouse. I need to validate this with a finger touch. ![image](https://user-images.githubusercontent.com/19823482/170295479-5a92f61e-e45f-42a3-ab5c-faa5642d850f.png)

Yep.
