### ISSUE TITLE
Enhancement for scatter points

### ISSUE THREAD

**Issue by don6019** [mp-007/kivy_matplotlib_widget#8]
Hello
I have been using the cursor example which you added - works well.
However I find this only works if there are lines present in the plot. If I only have scatter points it fails.
![scatter-pts](https://user-images.githubusercontent.com/36876292/188771011-5f752a0e-c0f5-48eb-aea6-7357048b5097.png)

In graph_generator:
```python
        self.ptid = ['1','2','3','4','5','6','7','8','9','10']
        self.x = [2,4,5,7,6,8,9,11,12,12]
        self.y = [1,2,3,4,5,6,7,8,9,10]

        fig,ax = plt.subplots(1)
        self.line1 = self.ax1.scatter(self.x, self.y, s=30, color='magenta', alpha=0.7, marker='x', picker=3)
        for i, ptlbl in enumerate(self.ptid):
            self.ax1.annotate(ptlbl, (self.x[i], self.y[i]),xytext=(5,0),textcoords='offset points',size=8,color='darkslategrey')
```
Also is there any way to be able to get the ptid (ptlbl annotation) for the picked point location.

**Comment by mp-007** [comment]
I should include scatter in my code. For the moment, I don't have a lot of time but I don't think it will not be difficult to add this feature.

**Comment by mp-007** [comment]
I have add scatter and multi xdata (ydata with same x value). I will share my code tomorrow has a beta version.

https://user-images.githubusercontent.com/19823482/190030851-368099a1-b4a7-4f6e-a082-4973e56e7bea.mp4

**Comment by mp-007** [comment]
@don6019 See my example in 'example_cusror_scatter_experimental' folder. 
For now, it's a experimental example (graph_widget.py has changed and it's different 'graph_widget.py' in main root).

change logs
1-add scatter (need to register scatter, see example_cusror_scatter_experimental/graph_generator.py)
2-draw annotation on cursor (note: no annotation on fast draw)
3-the example use fast draw (fps>60 during pan and zoom)
4-handle multi xdata (ydata with same x value)
5-add numpy in cursor algorithm (already a dependency for matplotlib, so no need of pure python search)

**Comment by mp-007** [comment]
I have add the ptid in the cursor label. Need to set scatter_label in figure widget (see main.py)

![image](https://user-images.githubusercontent.com/19823482/190468081-5cf8d72d-4f90-4903-91b0-077f74050812.png)
